import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../data/models/transaction_model.dart';

class PdfExportService {
  /// Generates and shares a formatted bank-statement PDF.
  static Future<void> exportTransactions(
    List<TransactionModel> transactions, {
    String userName = 'Account Holder',
    String bankName = 'SmartUSSD',
  }) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();
    final now = DateTime.now();
    final formatter = NumberFormat('#,##,##0.00', 'en_IN');
    final dateFormatter = DateFormat('dd MMM yyyy');

    // Summary numbers
    final totalIn = transactions
        .where((t) => t.type == 'received')
        .fold<double>(0, (s, t) => s + t.amount);
    final totalOut = transactions
        .where((t) => t.type == 'sent')
        .fold<double>(0, (s, t) => s + t.amount);
    final failed = transactions.where((t) => t.type == 'failed').length;

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (ctx) => _buildHeader(ctx, fontBold, bankName, userName, now),
        footer: (ctx) => _buildFooter(ctx, font, now),
        build: (ctx) => [
          // Summary boxes
          pw.Row(children: [
            _summaryBox('Total Received', '₹ ${formatter.format(totalIn)}',
                PdfColor.fromHex('#1B5E20'), PdfColor.fromHex('#E8F5E9'), fontBold, font),
            pw.SizedBox(width: 12),
            _summaryBox('Total Sent', '₹ ${formatter.format(totalOut)}',
                PdfColor.fromHex('#B71C1C'), PdfColor.fromHex('#FFEBEE'), fontBold, font),
            pw.SizedBox(width: 12),
            _summaryBox('Failed', '$failed transactions',
                PdfColor.fromHex('#E65100'), PdfColor.fromHex('#FFF3E0'), fontBold, font),
          ]),
          pw.SizedBox(height: 24),

          // Table header
          pw.Table(
            border: pw.TableBorder(
              horizontalInside: pw.BorderSide(
                color: PdfColor.fromHex('#E0E0E0'), width: 0.5),
              bottom: pw.BorderSide(color: PdfColor.fromHex('#E0E0E0'), width: 0.5),
            ),
            columnWidths: {
              0: const pw.FixedColumnWidth(72),
              1: const pw.FlexColumnWidth(2.5),
              2: const pw.FlexColumnWidth(1.2),
              3: const pw.FixedColumnWidth(60),
            },
            children: [
              // Header row
              pw.TableRow(
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('#3949AB'),
                ),
                children: [
                  _tableCell('Date', fontBold, isHeader: true),
                  _tableCell('Description', fontBold, isHeader: true),
                  _tableCell('Amount (₹)', fontBold,
                      isHeader: true, align: pw.TextAlign.right),
                  _tableCell('Status', fontBold, isHeader: true),
                ],
              ),
              // Data rows
              ...transactions.map((tx) {
                final isReceived = tx.type == 'received';
                final isFailed = tx.type == 'failed';
                return pw.TableRow(
                  children: [
                    _tableCell(
                        dateFormatter.format(tx.timestamp), font,
                        color: PdfColor.fromHex('#616161')),
                    _tableCell(tx.merchant, font),
                    _tableCell(
                      (isReceived ? '+' : '-') + formatter.format(tx.amount),
                      fontBold,
                      align: pw.TextAlign.right,
                      color: isFailed
                          ? PdfColor.fromHex('#E53935')
                          : isReceived
                              ? PdfColor.fromHex('#2E7D32')
                              : PdfColor.fromHex('#1A237E'),
                    ),
                    _tableCell(
                      isFailed
                          ? 'Failed'
                          : isReceived
                              ? 'Credit'
                              : 'Debit',
                      font,
                      color: isFailed
                          ? PdfColor.fromHex('#E53935')
                          : isReceived
                              ? PdfColor.fromHex('#2E7D32')
                              : PdfColor.fromHex('#1565C0'),
                    ),
                  ],
                );
              }),
            ],
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'This is a digital statement generated by SmartUSSD. '
            'Actual balances may differ. Contact your bank for official records.',
            style: pw.TextStyle(font: font, fontSize: 8,
                color: PdfColor.fromHex('#9E9E9E')),
          ),
        ],
      ),
    );

    // Share the PDF via Android share sheet
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename:
          'SmartUSSD_Statement_${DateFormat('yyyyMMdd').format(now)}.pdf',
    );
  }

  static pw.Widget _buildHeader(pw.Context ctx, pw.Font fontBold,
      String bankName, String userName, DateTime now) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 16),
      padding: const pw.EdgeInsets.symmetric(vertical: 12, horizontal: 16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#3949AB'),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('SmartUSSD',
                  style: pw.TextStyle(
                      font: fontBold,
                      fontSize: 18,
                      color: PdfColors.white)),
              pw.Text('Account Statement',
                  style: pw.TextStyle(
                      font: fontBold,
                      fontSize: 10,
                      color: PdfColor.fromHex('#C5CAE9'))),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(userName,
                  style: pw.TextStyle(
                      font: fontBold,
                      fontSize: 11,
                      color: PdfColors.white)),
              pw.Text('Generated: ${DateFormat('dd MMM yyyy, hh:mm a').format(now)}',
                  style: pw.TextStyle(
                      font: fontBold,
                      fontSize: 8,
                      color: PdfColor.fromHex('#C5CAE9'))),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context ctx, pw.Font font, DateTime now) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 8),
      padding: const pw.EdgeInsets.only(top: 6),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
            top: pw.BorderSide(color: PdfColors.grey300, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('SmartUSSD — Offline Banking Assistant',
              style: pw.TextStyle(font: font, fontSize: 8,
                  color: PdfColors.grey500)),
          pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(font: font, fontSize: 8,
                  color: PdfColors.grey500)),
        ],
      ),
    );
  }

  static pw.Widget _summaryBox(
    String label,
    String value,
    PdfColor textColor,
    PdfColor bgColor,
    pw.Font fontBold,
    pw.Font font,
  ) {
    return pw.Expanded(
      child: pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: bgColor,
          borderRadius: pw.BorderRadius.circular(8),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label,
                style: pw.TextStyle(font: font, fontSize: 9,
                    color: PdfColors.grey700)),
            pw.SizedBox(height: 4),
            pw.Text(value,
                style: pw.TextStyle(
                    font: fontBold, fontSize: 13, color: textColor)),
          ],
        ),
      ),
    );
  }

  static pw.Widget _tableCell(
    String text,
    pw.Font font, {
    bool isHeader = false,
    pw.TextAlign align = pw.TextAlign.left,
    PdfColor? color,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
      child: pw.Text(
        text,
        textAlign: align,
        style: pw.TextStyle(
          font: font,
          fontSize: isHeader ? 9 : 8.5,
          color: isHeader ? PdfColors.white : (color ?? PdfColors.black),
        ),
      ),
    );
  }
}
